version: 2

models:
    - name: orderss
      description: "orders dbt model"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null